### PR TITLE
feat(cansat-stm32f4): add buzzer support #59

### PR DESCRIPTION
**Pull request by 0xf4lc0n**
This PR adds support for buzzer as requested in #59.

### CODE REVIEW

**Comment by wiktorwieclaw** [comment]
Looks good, but I don't have a buzzer to verify if it works. @Bartosz-Slowik Could you run it?

**Review by Bartosz-Slowik — APPROVED** [review]
We might want some more functionality to this, but it looks good so far.

**Comment by Bartosz-Slowik** [comment]
We need to test the buzzer feature in the next meeting

**Comment by 0xf4lc0n** [comment]
@wiktorwieclaw Can we merge this PR? I've updated the buzz task to use the rtic 2.0 API.

**Pull request merged**
